### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by DishinIR** [freewms/zabbix-1c-service-template#6]
Special characters "\, ', ", `, *, ?, [, ], {, }, ~, $, !, &, ;, (, ), <, >, |, #, @, 0x0a" are not allowed in the parameters.

**Comment by freewms** [comment]
Скорее всего ошибка в userparameters_1c.conf

**Comment by freewms** [comment]
Можно в параметрах агента выставить "UnsafeUserParameters=1" - ошибка будет понятнее.

**Comment by DishinIR** [comment]
Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'Ошибка операции администрирования Администратор кластера не аутентифицирован'
